name: Deployment
on:
  push:
    branches:
      - master
#   pull_request:
#     branches:
#       - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Cache Maven packages
          #This action allows caching dependencies and build outputs to improve workflow execution time.
          uses: actions/cache@v1
          with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2
            #Run Tests
            - name: Run Tests
              run: mvn -B test
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: target/Demo3-0.0.1-SNAPSHOT.jar
          #           path: target/jar-file.jar

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact
      #Deploy the artifact (JAR) into AWS Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.MY_AWS_SECRET_KEY }}
          #aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          use_existing_version_if_available: false
          application_name: demo3
          environment_name: Demo3-env
          version_label: ${{github.SHA}}
          region: eu-central-1
          deployment_package: Demo3-0.0.1-SNAPSHOT.jar
